# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cezo_grpc import sample_pb2 as cezo__grpc_dot_sample__pb2


class SampleServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/sample_server.SampleServer/Connect',
                request_serializer=cezo__grpc_dot_sample__pb2.EmptyRequest.SerializeToString,
                response_deserializer=cezo__grpc_dot_sample__pb2.ConnectResponse.FromString,
                )
        self.Disconnect = channel.unary_unary(
                '/sample_server.SampleServer/Disconnect',
                request_serializer=cezo__grpc_dot_sample__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=cezo__grpc_dot_sample__pb2.EmptyResponse.FromString,
                )
        self.TryToJoinIteration = channel.unary_unary(
                '/sample_server.SampleServer/TryToJoinIteration',
                request_serializer=cezo__grpc_dot_sample__pb2.TryToJoinIterationRequest.SerializeToString,
                response_deserializer=cezo__grpc_dot_sample__pb2.TryToJoinIterationResponse.FromString,
                )
        self.SubmitIteration = channel.unary_unary(
                '/sample_server.SampleServer/SubmitIteration',
                request_serializer=cezo__grpc_dot_sample__pb2.SubmitIterationRequest.SerializeToString,
                response_deserializer=cezo__grpc_dot_sample__pb2.EmptyResponse.FromString,
                )
        self.ConnectEval = channel.unary_unary(
                '/sample_server.SampleServer/ConnectEval',
                request_serializer=cezo__grpc_dot_sample__pb2.EmptyRequest.SerializeToString,
                response_deserializer=cezo__grpc_dot_sample__pb2.ConnectResponse.FromString,
                )
        self.DisconnectEval = channel.unary_unary(
                '/sample_server.SampleServer/DisconnectEval',
                request_serializer=cezo__grpc_dot_sample__pb2.EmptyRequest.SerializeToString,
                response_deserializer=cezo__grpc_dot_sample__pb2.EmptyResponse.FromString,
                )
        self.TryToEval = channel.unary_unary(
                '/sample_server.SampleServer/TryToEval',
                request_serializer=cezo__grpc_dot_sample__pb2.EmptyRequest.SerializeToString,
                response_deserializer=cezo__grpc_dot_sample__pb2.TryToJoinIterationResponse.FromString,
                )
        self.SubmitEvaluation = channel.unary_unary(
                '/sample_server.SampleServer/SubmitEvaluation',
                request_serializer=cezo__grpc_dot_sample__pb2.SubmitEvaluationRequest.SerializeToString,
                response_deserializer=cezo__grpc_dot_sample__pb2.EmptyResponse.FromString,
                )


class SampleServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TryToJoinIteration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitIteration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectEval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectEval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TryToEval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitEvaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SampleServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=cezo__grpc_dot_sample__pb2.EmptyRequest.FromString,
                    response_serializer=cezo__grpc_dot_sample__pb2.ConnectResponse.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=cezo__grpc_dot_sample__pb2.DisconnectRequest.FromString,
                    response_serializer=cezo__grpc_dot_sample__pb2.EmptyResponse.SerializeToString,
            ),
            'TryToJoinIteration': grpc.unary_unary_rpc_method_handler(
                    servicer.TryToJoinIteration,
                    request_deserializer=cezo__grpc_dot_sample__pb2.TryToJoinIterationRequest.FromString,
                    response_serializer=cezo__grpc_dot_sample__pb2.TryToJoinIterationResponse.SerializeToString,
            ),
            'SubmitIteration': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitIteration,
                    request_deserializer=cezo__grpc_dot_sample__pb2.SubmitIterationRequest.FromString,
                    response_serializer=cezo__grpc_dot_sample__pb2.EmptyResponse.SerializeToString,
            ),
            'ConnectEval': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectEval,
                    request_deserializer=cezo__grpc_dot_sample__pb2.EmptyRequest.FromString,
                    response_serializer=cezo__grpc_dot_sample__pb2.ConnectResponse.SerializeToString,
            ),
            'DisconnectEval': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectEval,
                    request_deserializer=cezo__grpc_dot_sample__pb2.EmptyRequest.FromString,
                    response_serializer=cezo__grpc_dot_sample__pb2.EmptyResponse.SerializeToString,
            ),
            'TryToEval': grpc.unary_unary_rpc_method_handler(
                    servicer.TryToEval,
                    request_deserializer=cezo__grpc_dot_sample__pb2.EmptyRequest.FromString,
                    response_serializer=cezo__grpc_dot_sample__pb2.TryToJoinIterationResponse.SerializeToString,
            ),
            'SubmitEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitEvaluation,
                    request_deserializer=cezo__grpc_dot_sample__pb2.SubmitEvaluationRequest.FromString,
                    response_serializer=cezo__grpc_dot_sample__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sample_server.SampleServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SampleServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample_server.SampleServer/Connect',
            cezo__grpc_dot_sample__pb2.EmptyRequest.SerializeToString,
            cezo__grpc_dot_sample__pb2.ConnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample_server.SampleServer/Disconnect',
            cezo__grpc_dot_sample__pb2.DisconnectRequest.SerializeToString,
            cezo__grpc_dot_sample__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TryToJoinIteration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample_server.SampleServer/TryToJoinIteration',
            cezo__grpc_dot_sample__pb2.TryToJoinIterationRequest.SerializeToString,
            cezo__grpc_dot_sample__pb2.TryToJoinIterationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitIteration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample_server.SampleServer/SubmitIteration',
            cezo__grpc_dot_sample__pb2.SubmitIterationRequest.SerializeToString,
            cezo__grpc_dot_sample__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectEval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample_server.SampleServer/ConnectEval',
            cezo__grpc_dot_sample__pb2.EmptyRequest.SerializeToString,
            cezo__grpc_dot_sample__pb2.ConnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisconnectEval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample_server.SampleServer/DisconnectEval',
            cezo__grpc_dot_sample__pb2.EmptyRequest.SerializeToString,
            cezo__grpc_dot_sample__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TryToEval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample_server.SampleServer/TryToEval',
            cezo__grpc_dot_sample__pb2.EmptyRequest.SerializeToString,
            cezo__grpc_dot_sample__pb2.TryToJoinIterationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sample_server.SampleServer/SubmitEvaluation',
            cezo__grpc_dot_sample__pb2.SubmitEvaluationRequest.SerializeToString,
            cezo__grpc_dot_sample__pb2.EmptyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
