# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cezo_grpc/sample.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cezo_grpc/sample.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63\x65zo_grpc/sample.proto\x12\rsample_server\"\x0e\n\x0c\x45mptyRequest\"\x0f\n\rEmptyResponse\":\n\x0f\x43onnectResponse\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\x12\x13\n\x0b\x63lientIndex\x18\x02 \x01(\x05\"0\n\x19TryToJoinIterationRequest\x12\x13\n\x0b\x63lientIndex\x18\x01 \x01(\x05\"0\n\x1aTryToJoinIterationResponse\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\"/\n\x18PullGradsAndSeedsRequest\x12\x13\n\x0b\x63lientIndex\x18\x01 \x01(\x05\"\x83\x01\n\x19PullGradsAndSeedsResponse\x12.\n\x05seeds\x18\x01 \x01(\x0b\x32\x1f.sample_server.ListOfListOfInts\x12\x36\n\x05grads\x18\x02 \x01(\x0b\x32\'.sample_server.ListOfListOfListOfFloats\"\x1a\n\nListOfInts\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x05\";\n\x10ListOfListOfInts\x12\'\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x19.sample_server.ListOfInts\"\x1c\n\x0cListOfFloats\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\"?\n\x12ListOfListOfFloats\x12)\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1b.sample_server.ListOfFloats\"K\n\x18ListOfListOfListOfFloats\x12/\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32!.sample_server.ListOfListOfFloats\"X\n\x16SubmitIterationRequest\x12>\n\x13local_update_result\x18\x01 \x01(\x0b\x32!.sample_server.ListOfListOfFloats2\x88\x03\n\x0cSampleServer\x12H\n\x07\x43onnect\x12\x1b.sample_server.EmptyRequest\x1a\x1e.sample_server.ConnectResponse\"\x00\x12k\n\x12TryToJoinIteration\x12(.sample_server.TryToJoinIterationRequest\x1a).sample_server.TryToJoinIterationResponse\"\x00\x12h\n\x11PullGradsAndSeeds\x12\'.sample_server.PullGradsAndSeedsRequest\x1a(.sample_server.PullGradsAndSeedsResponse\"\x00\x12W\n\x0fSubmitIteration\x12%.sample_server.SubmitIterationRequest\x1a\x1b.sample_server.EmptyRequest\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cezo_grpc.sample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=41
  _globals['_EMPTYREQUEST']._serialized_end=55
  _globals['_EMPTYRESPONSE']._serialized_start=57
  _globals['_EMPTYRESPONSE']._serialized_end=72
  _globals['_CONNECTRESPONSE']._serialized_start=74
  _globals['_CONNECTRESPONSE']._serialized_end=132
  _globals['_TRYTOJOINITERATIONREQUEST']._serialized_start=134
  _globals['_TRYTOJOINITERATIONREQUEST']._serialized_end=182
  _globals['_TRYTOJOINITERATIONRESPONSE']._serialized_start=184
  _globals['_TRYTOJOINITERATIONRESPONSE']._serialized_end=232
  _globals['_PULLGRADSANDSEEDSREQUEST']._serialized_start=234
  _globals['_PULLGRADSANDSEEDSREQUEST']._serialized_end=281
  _globals['_PULLGRADSANDSEEDSRESPONSE']._serialized_start=284
  _globals['_PULLGRADSANDSEEDSRESPONSE']._serialized_end=415
  _globals['_LISTOFINTS']._serialized_start=417
  _globals['_LISTOFINTS']._serialized_end=443
  _globals['_LISTOFLISTOFINTS']._serialized_start=445
  _globals['_LISTOFLISTOFINTS']._serialized_end=504
  _globals['_LISTOFFLOATS']._serialized_start=506
  _globals['_LISTOFFLOATS']._serialized_end=534
  _globals['_LISTOFLISTOFFLOATS']._serialized_start=536
  _globals['_LISTOFLISTOFFLOATS']._serialized_end=599
  _globals['_LISTOFLISTOFLISTOFFLOATS']._serialized_start=601
  _globals['_LISTOFLISTOFLISTOFFLOATS']._serialized_end=676
  _globals['_SUBMITITERATIONREQUEST']._serialized_start=678
  _globals['_SUBMITITERATIONREQUEST']._serialized_end=766
  _globals['_SAMPLESERVER']._serialized_start=769
  _globals['_SAMPLESERVER']._serialized_end=1161
# @@protoc_insertion_point(module_scope)
